/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-10-29")
public class Attribute implements org.apache.thrift.TBase<Attribute, Attribute._Fields>, java.io.Serializable, Cloneable, Comparable<Attribute> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Attribute");

  private static final org.apache.thrift.protocol.TField ATTR_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("attrName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ATTR_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("attrType", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AttributeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AttributeTupleSchemeFactory();

  public java.lang.String attrName; // required
  /**
   * 
   * @see column_type
   */
  public column_type attrType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ATTR_NAME((short)1, "attrName"),
    /**
     * 
     * @see column_type
     */
    ATTR_TYPE((short)2, "attrType");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ATTR_NAME
          return ATTR_NAME;
        case 2: // ATTR_TYPE
          return ATTR_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ATTR_NAME, new org.apache.thrift.meta_data.FieldMetaData("attrName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ATTR_TYPE, new org.apache.thrift.meta_data.FieldMetaData("attrType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, column_type.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Attribute.class, metaDataMap);
  }

  public Attribute() {
  }

  public Attribute(
    java.lang.String attrName,
    column_type attrType)
  {
    this();
    this.attrName = attrName;
    this.attrType = attrType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Attribute(Attribute other) {
    if (other.isSetAttrName()) {
      this.attrName = other.attrName;
    }
    if (other.isSetAttrType()) {
      this.attrType = other.attrType;
    }
  }

  public Attribute deepCopy() {
    return new Attribute(this);
  }

  @Override
  public void clear() {
    this.attrName = null;
    this.attrType = null;
  }

  public java.lang.String getAttrName() {
    return this.attrName;
  }

  public Attribute setAttrName(java.lang.String attrName) {
    this.attrName = attrName;
    return this;
  }

  public void unsetAttrName() {
    this.attrName = null;
  }

  /** Returns true if field attrName is set (has been assigned a value) and false otherwise */
  public boolean isSetAttrName() {
    return this.attrName != null;
  }

  public void setAttrNameIsSet(boolean value) {
    if (!value) {
      this.attrName = null;
    }
  }

  /**
   * 
   * @see column_type
   */
  public column_type getAttrType() {
    return this.attrType;
  }

  /**
   * 
   * @see column_type
   */
  public Attribute setAttrType(column_type attrType) {
    this.attrType = attrType;
    return this;
  }

  public void unsetAttrType() {
    this.attrType = null;
  }

  /** Returns true if field attrType is set (has been assigned a value) and false otherwise */
  public boolean isSetAttrType() {
    return this.attrType != null;
  }

  public void setAttrTypeIsSet(boolean value) {
    if (!value) {
      this.attrType = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ATTR_NAME:
      if (value == null) {
        unsetAttrName();
      } else {
        setAttrName((java.lang.String)value);
      }
      break;

    case ATTR_TYPE:
      if (value == null) {
        unsetAttrType();
      } else {
        setAttrType((column_type)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ATTR_NAME:
      return getAttrName();

    case ATTR_TYPE:
      return getAttrType();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ATTR_NAME:
      return isSetAttrName();
    case ATTR_TYPE:
      return isSetAttrType();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Attribute)
      return this.equals((Attribute)that);
    return false;
  }

  public boolean equals(Attribute that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_attrName = true && this.isSetAttrName();
    boolean that_present_attrName = true && that.isSetAttrName();
    if (this_present_attrName || that_present_attrName) {
      if (!(this_present_attrName && that_present_attrName))
        return false;
      if (!this.attrName.equals(that.attrName))
        return false;
    }

    boolean this_present_attrType = true && this.isSetAttrType();
    boolean that_present_attrType = true && that.isSetAttrType();
    if (this_present_attrType || that_present_attrType) {
      if (!(this_present_attrType && that_present_attrType))
        return false;
      if (!this.attrType.equals(that.attrType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAttrName()) ? 131071 : 524287);
    if (isSetAttrName())
      hashCode = hashCode * 8191 + attrName.hashCode();

    hashCode = hashCode * 8191 + ((isSetAttrType()) ? 131071 : 524287);
    if (isSetAttrType())
      hashCode = hashCode * 8191 + attrType.getValue();

    return hashCode;
  }

  @Override
  public int compareTo(Attribute other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetAttrName()).compareTo(other.isSetAttrName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttrName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attrName, other.attrName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAttrType()).compareTo(other.isSetAttrType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttrType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attrType, other.attrType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Attribute(");
    boolean first = true;

    sb.append("attrName:");
    if (this.attrName == null) {
      sb.append("null");
    } else {
      sb.append(this.attrName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("attrType:");
    if (this.attrType == null) {
      sb.append("null");
    } else {
      sb.append(this.attrType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AttributeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AttributeStandardScheme getScheme() {
      return new AttributeStandardScheme();
    }
  }

  private static class AttributeStandardScheme extends org.apache.thrift.scheme.StandardScheme<Attribute> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Attribute struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ATTR_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.attrName = iprot.readString();
              struct.setAttrNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ATTR_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.attrType = column_type.findByValue(iprot.readI32());
              struct.setAttrTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Attribute struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.attrName != null) {
        oprot.writeFieldBegin(ATTR_NAME_FIELD_DESC);
        oprot.writeString(struct.attrName);
        oprot.writeFieldEnd();
      }
      if (struct.attrType != null) {
        oprot.writeFieldBegin(ATTR_TYPE_FIELD_DESC);
        oprot.writeI32(struct.attrType.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AttributeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AttributeTupleScheme getScheme() {
      return new AttributeTupleScheme();
    }
  }

  private static class AttributeTupleScheme extends org.apache.thrift.scheme.TupleScheme<Attribute> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Attribute struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAttrName()) {
        optionals.set(0);
      }
      if (struct.isSetAttrType()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetAttrName()) {
        oprot.writeString(struct.attrName);
      }
      if (struct.isSetAttrType()) {
        oprot.writeI32(struct.attrType.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Attribute struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.attrName = iprot.readString();
        struct.setAttrNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.attrType = column_type.findByValue(iprot.readI32());
        struct.setAttrTypeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

