// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Ginkgo.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class GinkgoHandler : virtual public GinkgoIf {
 public:
  GinkgoHandler() {
    // Your initialization goes here
  }

  void get_tables_meta(std::vector<TTableDescriptor> & _return) {
    // Your implementation goes here
    printf("get_tables_meta\n");
  }

  void get_table_descriptor(TTableDescriptor& _return, const std::string& table_name) {
    // Your implementation goes here
    printf("get_table_descriptor\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<GinkgoHandler> handler(new GinkgoHandler());
  shared_ptr<TProcessor> processor(new GinkgoProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

