/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef table_CONSTANTS_H
#define table_CONSTANTS_H

#include "table_types.h"



class tableConstants {
 public:
  tableConstants();

};

extern const tableConstants g_table_constants;



#endif
