/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CalciteServer_constants.h"



const CalciteServerConstants g_CalciteServer_constants;

CalciteServerConstants::CalciteServerConstants() {
}



