/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CalciteServer_CONSTANTS_H
#define CalciteServer_CONSTANTS_H

#include "CalciteServer_types.h"



class CalciteServerConstants {
 public:
  CalciteServerConstants();

};

extern const CalciteServerConstants g_CalciteServer_constants;



#endif
